theme = "modus_vivendi_tinted"

[editor]
bufferline = "multiple"
rulers = [80]
true-color = true
undercurl = true
end-of-line-diagnostics = "hint"
color-modes = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.lsp]
display-progress-messages = true

[keys.normal.space]
i = ":toggle lsp.display-inlay-hints"
B = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"

[keys.normal]
C-p = ":sh echo %{buffer_name} | pbcopy"
